# The razor application, for fundraising.
[package]
name = "signer"
version = "0.1.0"
edition = "2021"

[features]
default = ["testing"]
integration-tests = ["testing"]
testing = ["fake", "mockall", "sbtc/testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aquamarine.workspace = true
axum.workspace = true
backoff.workspace = true
bincode.workspace = true
bitcoin = { workspace = true, features = ["rand-std"] }
bitcoincore-rpc.workspace = true
bitcoincore-rpc-json.workspace = true
bitvec = { workspace = true, default-features = false, features = ["std"] }
blocklist-api = { path = "../.generated-sources/blocklist-api" }
emily-client = { path = "../.generated-sources/emily/client/rust" }
clap.workspace = true
clarity.workspace = true
config = "0.14"
futures.workspace = true
hashbrown.workspace = true
libp2p.workspace = true
p256k1.workspace = true
prost.workspace = true
rand.workspace = true
reqwest.workspace = true
sbtc = { path = "../sbtc", default-features = false }
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
stackslib.workspace = true
stacks-common.workspace = true
strum.workspace = true
thiserror.workspace = true
time.workspace = true
tonic.workspace = true
tokio = { workspace = true, features = ["signal", "macros", "rt-multi-thread"] }
tokio-stream.workspace = true
tracing.workspace = true
tracing-attributes.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
# wsts.workspace = true
wsts = { git = "https://github.com/Trust-Machines/wsts.git", rev = "e214f39d13b36f22a28e2455461b6eb92997521e" }
zeromq.workspace = true
hex.workspace = true
cfg-if = "1.0"
include_dir = "0.7.4"

# Only for testing
mockall = { version = "0.12.1", optional = true }
fake = { version = "2.9.2", features = ["derive", "time"], optional = true }

[dependencies.secp256k1]
version = "*"
features = ["rand-std", "global-context"]

[dev-dependencies]
bitcoincore-rpc.workspace = true
mockito = "1.4.0"
more-asserts = "0.3"
ripemd = "0.1.3"
sbtc = { path = "../sbtc", default-features = false, features = ["testing"] }
test-case = "3.1"
test-log = { version = "0.2.16", default-features = false, features = ["trace"] }


[build-dependencies]
tonic-build.workspace = true
